//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PascalTraining.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PascalTraining.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DB Auth. Setup.
        /// </summary>
        public static string AzureDatabaseAuthenticationSetup {
            get {
                return ResourceManager.GetString("AzureDatabaseAuthenticationSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure DB Setup.
        /// </summary>
        public static string AzureDatabaseSetup {
            get {
                return ResourceManager.GetString("AzureDatabaseSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Database Authentication Setup.
        /// </summary>
        public static string AzureDBAuthSetup {
            get {
                return ResourceManager.GetString("AzureDBAuthSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Database Setup.
        /// </summary>
        public static string AzureDBSetup {
            get {
                return ResourceManager.GetString("AzureDBSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blazor Web App.
        /// </summary>
        public static string BlazorWebApp {
            get {
                return ResourceManager.GetString("BlazorWebApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation VS 2022.
        /// </summary>
        public static string InstallationVS2022 {
            get {
                return ResourceManager.GetString("InstallationVS2022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize an App.
        /// </summary>
        public static string LocalizeAnApp {
            get {
                return ResourceManager.GetString("LocalizeAnApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localize.
        /// </summary>
        public static string LocalizePageTitle {
            get {
                return ResourceManager.GetString("LocalizePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Readme.md.
        /// </summary>
        public static string Readme {
            get {
                return ResourceManager.GetString("Readme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typescript Front End.
        /// </summary>
        public static string TypescriptFrontEnd {
            get {
                return ResourceManager.GetString("TypescriptFrontEnd", resourceCulture);
            }
        }
    }
}
